linters:
  RuboCop:
    enabled: false

  Tab:
    enabled: false

  TrailingBlankLines:
    enabled: false

  TrailingWhitespace:
    enabled: false

  LineLength:
    enabled: false

skip_frontmatter: true
